Process defer _run_with_lock
canonical/charm-rolling-ops pull request #10
Opened 2024-02-08 22:25 UTC by phvalguima

Extends _run_with_lock method to:
* Capture errors from callback() method
* Process deferred action set by the callback()

2024-02-16 11:36 UTC, phvalguima commented on lib/charms/rolling_ops/v0/rollingops.py
> +            event.defer()
@marcoppenheimer we need to decide if a defer here makes sense. I think it is safe to abandon this event and wait for an actual hook.

2024-02-16 15:42 UTC, phvalguima commented on lib/charms/rolling_ops/v0/rollingops.py
> +            event.defer()
We need it.

2024-02-16 16:00 UTC, delgod commented on lib/charms/rolling_ops/v0/rollingops.py
> +            relation.data[self.charm.unit]["retry-count"] = str(int(relation.data[self.charm.unit].get("retry-count", 0)) + 1)
Do we need to have this counter in databag? I don't see that we actually using value

2024-02-16 16:07 UTC, phvalguima commented on lib/charms/rolling_ops/v0/rollingops.py
> +            relation.data[self.charm.unit]["retry-count"] = str(int(relation.data[self.charm.unit].get("retry-count", 0)) + 1)
Yes, because just "acquire_lock" will try to set the lock status as "acquire". If the value present there is already "acquire" (i.e. we did not clean up the previous status, e.g. in a past failure), then there is no relation changed in the databag, hence, no real event is triggered to other units.

2024-02-17 00:09 UTC, marcoppenheimer requested changes

2024-02-17 00:09 UTC, marcoppenheimer commented on lib/charms/rolling_ops/v0/rollingops.py
> +            event.defer()
I don't think we do?

I have just:
```python
        if self.name not in os.environ.get("JUJU_DISPATCH_PATH", ""):
            return
```

in https://github.com/canonical/zookeeper-k8s-operator/pull/65, which is giving:

```
unit-zookeeper-1: 23:51:00 INFO unit.zookeeper/1.juju-log restart:2: zookeeper/1 restarting...
unit-zookeeper-2: 23:51:09 INFO unit.zookeeper/2.juju-log restart:2: zookeeper/2 restarting...
unit-zookeeper-0: 23:51:16 INFO unit.zookeeper/0.juju-log restart:2: zookeeper/0 restarting...
unit-zookeeper-0: 23:51:25 INFO unit.zookeeper/0.juju-log restart:2: zookeeper/0 restarting...
unit-zookeeper-1: 23:51:33 INFO unit.zookeeper/1.juju-log restart:2: zookeeper/1 restarting...
unit-zookeeper-2: 23:51:42 INFO unit.zookeeper/2.juju-log restart:2: zookeeper/2 restarting...
unit-zookeeper-0: 23:51:49 INFO unit.zookeeper/0.juju-log restart:2: zookeeper/0 restarting...
```

2024-02-17 00:09 UTC, marcoppenheimer commented on lib/charms/rolling_ops/v0/rollingops.py
> +            relation.data[self.charm.unit]["retry-count"] = str(int(relation.data[self.charm.unit].get("retry-count", 0)) + 1)
I agree with Mykola, I'm not sure we need the retry count.
In this scenario, a unit has erroneously deferred the callback. So instead, we try to re-acquire a lock, which will set relation-changed, other units will complete their lock-holding, set release, and this unit gets granted a new lock.

I think we should remove all of the handling in `run_with_lock`, as I'm not sure it solves the specific problem of mis-matched relation-data.

2024-02-17 00:10 UTC, marcoppenheimer commented on lib/charms/rolling_ops/v0/rollingops.py
> +            event.defer()
What are you seeing that necessitates it?

2024-02-23 11:27 UTC, phvalguima commented on lib/charms/rolling_ops/v0/rollingops.py
> +            event.defer()
This is related to the bug #13. I am breaking this PR from that issue, as it was supposed to focus on how to handle a retry if `run-with-lock` defers.

2024-04-22 20:56 UTC, taurus-forever commented
@phvalguima abandon if favour of upcoming LIBAPI=1 from OpenSearch?

2024-04-22 20:56 UTC, closed without merging

2024-04-23 05:48 UTC, phvalguima commented
@taurus-forever we can close. However, we have on one side, a code we've been using for years and we now know its main issues; vs. a code we will be still discovering new things. The latter should not be considered `v1`.